// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uc_10_Wendel_Relacionamentos_Codigo_00004.Data;

#nullable disable

namespace Uc_10_Wendel_Relacionamentos_Codigo_00004.Migrations
{
    [DbContext(typeof(Uc_10_Wendel_Relacionamentos_Codigo_00004Context))]
    partial class Uc_10_Wendel_Relacionamentos_Codigo_00004ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uc_10_Wendel_Relacionamentos_Codigo_00004.Models.Automovel", b =>
                {
                    b.Property<int>("AutomovelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutomovelID"));

                    b.Property<int>("MarcaID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutomovelID");

                    b.HasIndex("MarcaID");

                    b.ToTable("Automovel");
                });

            modelBuilder.Entity("Uc_10_Wendel_Relacionamentos_Codigo_00004.Models.Marca", b =>
                {
                    b.Property<int>("MarcaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaID"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaID");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("Uc_10_Wendel_Relacionamentos_Codigo_00004.Models.Automovel", b =>
                {
                    b.HasOne("Uc_10_Wendel_Relacionamentos_Codigo_00004.Models.Marca", "Marca")
                        .WithMany("Automoveis")
                        .HasForeignKey("MarcaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Uc_10_Wendel_Relacionamentos_Codigo_00004.Models.Marca", b =>
                {
                    b.Navigation("Automoveis");
                });
#pragma warning restore 612, 618
        }
    }
}
